### ISSUE TITLE
Does not work in Firefox 57 and up

### ISSUE THREAD

**Issue by ronaldpk** [zendtech/zend-debugger-firefox#2]
Firefox has dropped support for what they call legacy add-ons. https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing So the debugger toolbar no longer works: it has been disabled and there is no way to enable it.

**Comment by yescsabi** [comment]
Are you planning an update for FF 57+ support soon?

**Comment by stephansch321** [comment]
an update would be great!

**Comment by speedbomb** [comment]
Looking forward to use the Zend Toolbar again in Firefox...

**Comment by yescsabi** [comment]
Do you guys know an alternative?

**Comment by ronaldpk** [comment]
@yescsabi  Chrome. There are a number of working Zend debugger extensions.

**Comment by clarkphp** [comment]
There is one here you can try: https://addons.mozilla.org/en-US/firefox/addon/zend-debugger-button/

**Comment by speedbomb** [comment]
Hi @clarkphp , thanks for the hint: It works very well!

**Comment by kaloyan-raev** [comment]
We are rewriting the toolbar to use the new WebExtensions API. The current work in progress is in the https://github.com/zendtech/zend-debugger-firefox/tree/web-ext branch.

It can be tested following the instructions here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

Currently works:
- Debug current page
- Debug next page
- Profile current page
- Settings

Todo:
- Debug all forms
- Debug all pages
- Frame selection

**Comment by kaloyan-raev** [comment]
The rewrite to WebExtensions API is complete: https://github.com/zendtech/zend-debugger-firefox/pull/3

It is released as version 4.0 at Mozilla Add-ons: https://addons.mozilla.org/en-US/firefox/addon/zend-debugger-toolbar/

The only feature missing compared to the old version is "Frame selection". I couldn't find how to implement it properly with the new API. By the way, this feature is not available in Z-Ray too, so I suspect it is not as important now-a-days as it was in the past. If I am wrong, please open an issue about this.
